### ISSUE TITLE
Error when importing Local module

### ISSUE THREAD

**Issue by kingsleyh** [JohnBugner/elm-storage#1]
Hi

I tried to you this module - but when I import it into my project I get an error in the browser:

```
    app.js:170 Uncaught TypeError: Cannot read property 'nativeBinding' of undefined
    at app.js:170
    at app.js:201
    at app.js:13912
```

```
line 170: var keys = _elm_lang$core$Native_Scheduler.nativeBinding(function(callback) {
```

I'm using Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by kingsleyh** [comment]
I think it's related to keys and clear not being wrapped in functions and just being referenced as vars - If I commend out keys, clear - it starts working.

**Comment by JohnBugner** [comment]
(1) This module used to work, but Evan keeps changing the JS format that Elm gets converted into, hence the error. (For this reason, he discourages writing native modules, which is what this is, unfortunately.)
(2) What lines are you commenting out exactly? I'm not sure how that would fix anything.

**Comment by kingsleyh** [comment]
Hey

I forked it and got it working by wrapping with functions

**Comment by JohnBugner** [comment]
So, I got around to looking at this now. Your change makes the module compile, but calling "keys" or "clear" creates an internal error. (If you don't need these functions, none of this matters, because the other functions still work.) I'm don't know how to fix it, because I don't know what the syntax is for an internal scheduled function that takes 0 parameters. I'm actually surprised the other functions still work at all, because the internal format seems to have changed once again. Take https://github.com/elm-lang/core/tree/master/src , The js files are no longer in /Native, but now in /Elm/Kernel.

Hopefully Evan just releases the (persistent) cache library soon. If it's part of 0.19, then it probably won't be out until 2018 though.

**Comment by JohnBugner** [comment]
So, I fixed it by just giving the native functions of "keys" and "clear" a dummy variable that is just ignored. Good enough.
